--- 
- name: Refresh Host Inventory at Runtime and Add a Pause while Executing Playbook
  hosts: localhost
  vars: 
    hostpath: "./hosts.ini"
    hoststring: "ansible_user=ec2-user"
  connection: ssh
  gather_facts: True
  lineinfile: dest={{ hostpath }}
              regexp={{ item.public_ip }} 
              insertafter="[webserver]" 
              line="{{ item.public_ip }} {{hoststring}}"
              state=present
 
  tasks:
    - meta: refresh_inventory
 
    - pause:
        minutes: 1
